apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ci
  name: jenkins-role
rules:
  - apiGroups: [""]
    resources: ["secrets", "pods", "services", "deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-binding
  namespace: ci
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ci
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
