apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-servicie
  namespace: garage-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle
  template:
    metadata:
      labels:
        app: vehicle
    spec:
      containers:
      - name: vehicle
        image: vehicle-service:latest
        imagePullPolicy: IfNotPresent     
        ports:
        - containerPort: 8180
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
spec:
  selector:
    app: vehicle
  ports:
  - port: 8180
    targetPort: 8180
  type: ClusterIP

