discovery-service:
  enabled: true
  image:
    tag: "1.0.0"

vehicle-service:
  enabled: true
  image:
    tag: "1.0.1"

api-gateway:
  enabled: true
  image:
    tag: "1.0.2"

vehicle-db:
  enabled: true
  image:
    tag: "1.0.3"
