discovery-service:
  service:
    port: 8761
  enabled: true
  image:
    tag: "1.0.0"

vehicle-service:
  service:
    port: 8180
    type: ClusterIP
  enabled: true
  image:
    tag: "1.0.1"

api-gateway:
  service:
    port: 8080
  enabled: true
  image:
    tag: "1.0.2"

vehicle-db:
  service:
    port: 5432
  enabled: true
  image:
    tag: "1.0.3"
